/**
 *    This file was auto generated by angular schematics.
 *
 *    For update use script from package.json
 */

export interface ColorData {
    type: 'color' | 'box-shadow' | 'none';
    rgba?: string;
    hex?: string;
    r?: number;
    g?: number;
    b?: number;
    a?: number;
    boxShadowParams?: string[];
  }
  
  export interface ColorsMap {
    <% for (let mapValue of colorsMaps[0].mapValues) { %>
      /** as theme map variable <%= mapValue.name %> */
      <%= camelize(mapValue.name) %>: ColorData;
    <% } %>
  }