/**
 *  This file was auto generated by angular schematics.
 *  For update use script from package.json
 */

import { ColorsMap } from './generated-types';

<% for (let colorsMap of colorsMaps) { %>
export const <%= camelize(colorsMap.mapName) %>: ColorsMap = {
  <% for (let mapValue of colorsMap.mapValues) { %>
    /** as theme map variable <%= mapValue.name %> */
    <%= camelize(mapValue.name) %>: { 
      type: '<%= mapValue.value.type %>',
      <%if (mapValue.value.type !== 'none') {%>
        rgba: '<%= mapValue.value.rgba %>',
        hex: '<%= mapValue.value.hex %>',
        r: <%= mapValue.value.r %>,
        g: <%= mapValue.value.g %>,
        b: <%= mapValue.value.b %>,
        a: <%= mapValue.value.a %>,
        <%if (mapValue.value.boxShadowParams) {%>
        boxShadowParams: [
          <% for (let param of mapValue.value.boxShadowParams) { %>
            '<%= param %>',
          <%} %>
        ],
        <%} %>
      <%} %>
    },
  <% } %>
};
<% } %>