/**
 *    This file was auto generated by angular schematics.
 *
 *    For update use script from package.json
 */

export interface FontData {
    fontStyle: string;
    fontWeight: string;
    fontSize: string;
    lineHeight: string;
    letterSpacing: string;
    textTransform: string;
  }
  