/**
 *  This file was auto generated by angular schematics.
 *  For update use script from package.json
 */

import { FontData } from './generated-types';

<% for (let variable of variables) { %>
  <%if (variable.type === 'variable') {%>
    /** <%= variable.name %> SASS variable */
    export const <%= camelize(variable.name) %>: string = '<%= variable.value %>';
  <%} %>

  <%if (variable.type === 'map') {%>
    /** <%= variable.mapName %> SASS variable */
    export const <%= camelize(variable.mapName) %>: FontData = {
      <% for (let mapValue of variable.mapValues) { %>
        '<%= mapValue.paramName %>': '<%= mapValue.paramValue %>',
      <% } %>
    };
    <% } %>
  <%} %> 