/**
 *  This file was auto generated by angular schematics.
 *  For update use script from package.json
 */

import { FontData } from './generated-types';

/** $font-family SASS variable */
export const $fontFamily: string = 'Graphic LCG';
